# -*- coding:utf-8 -*-
from . import ventas_heredanproductos
from . import personas_tipocredito
from . import ventasheredado
from . import inventario
from . import grados_estudios
from . import nombre_cuentas_email
from . import autos
from . import personas
from . import unicontacto
from . import Computermodel
from . import depends
